Fix Integration Test Failure When PO Box Config Changes
workarea-commerce/workarea-paypal pull request #1
Opened 2019-08-27 16:44 UTC by tubbo

When `config.allow_shipping_address_po_box` is set to `true`, an
integration test in the PayPal plugin failed due to the shipping step
raising an error since no shipping option is available for the address.
To ensure the test is configured correctly, it's now wrapped in a
`Workarea.with_config` block, with `config.allow_shipping_address_po_box`
set to `false`. This allows the test to ensure that the proper redirect
occurs when a shipping address coming back from PayPal is invalid.

PAYPAL-83

2019-08-28 13:58 UTC, bencrouse requested changes

2019-08-28 13:58 UTC, bencrouse commented on app/models/workarea/checkout/steps/shipping.decorator
> +    rescue Checkout::Steps::Shipping::NoAvailableShippingOption
Why do we want to swallow this error here?

2019-08-28 13:58 UTC, bencrouse commented on test/integration/workarea/storefront/paypal_integration_test.rb
> +        @_allow_po_box = Workarea.config.allow_shipping_address_po_box
No need for an instance variable here.

2019-08-28 13:58 UTC, bencrouse commented on test/integration/workarea/storefront/paypal_integration_test.rb
> +        Workarea.config.allow_shipping_address_po_box = true
Is this for v3.5 and forward only? We added the automatic config resetting as part of v3.5...

2019-08-28 16:54 UTC, tubbo commented on test/integration/workarea/storefront/paypal_integration_test.rb
> +        Workarea.config.allow_shipping_address_po_box = true
in theory, this version of workarea-paypal can be used for either v3.4 or v3.5, so I did this just to make sure it won't leak on older versions.

2019-09-05 13:31 UTC, bencrouse submitted a review, later dismissed

2019-09-05 13:31 UTC, bencrouse commented on app/models/workarea/checkout/steps/shipping.decorator
> +    rescue Checkout::Steps::Shipping::NoAvailableShippingOption
So.....

2019-09-05 16:37 UTC, tubbo commented
After reviewing what the test actually does, it's clear that the configuration setting was just unexpected from the default. The address in the test _was_ invalid, and the test was ensuring that such an invalid address would be redirected properly. I basically just wrapped the test in a `Workarea.with_config` so that the error doesn't get thrown, and the proper redirection steps take place.

2019-09-06 13:25 UTC, bencrouse approved these changes

2019-09-06 13:25 UTC, merged