Monkey Patch BN Code Into Gateway
workarea-commerce/workarea-paypal pull request #19
Opened 2020-09-10 23:04 UTC by tubbo

This prevents any kind of configuration issues disrupting the Workarea->PayPal reporting flow.

2020-09-11 03:48 UTC, mttdffy requested changes
Should we take out the bits that I added to the auto config stuff?

2020-09-11 12:42 UTC, bencrouse requested changes
+1 to @mttdffy 's comment, also can we get a unit test over this?

2020-09-11 13:38 UTC, tubbo commented
@bencrouse @mttdffy I would love to write a unit test for this, but I don't have any PayPal credentials and I can't seem to obtain them. Tried for about an hour yesterday, but all I can come up with are existing credentials and an inability to generate more. Might have just been looking down the wrong path though.

2020-09-11 14:58 UTC, mttdffy commented
> I don't have any PayPal credentials

FWIW we have PayPal creds in our shared password vault. They were setup for the newer API but they might still work for this one.

2020-09-11 17:51 UTC, tubbo commented on test/workarea/paypal/ext/active_merchant/paypal_express_gateway_test.rb
> +        xml = Builder::XmlMarkup.new
Xml Builder is what's used in the gateway: https://github.com/activemerchant/active_merchant/blob/1648fed6eb5cee78878d08e7418a2a44475c044e/lib/active_merchant/billing/gateways/paypal/paypal_common_api.rb#L312

2020-09-14 13:32 UTC, bencrouse approved these changes

2020-09-14 13:33 UTC, merged